# yaml-language-server: $schema=https://www.schemastore.org/github-action.json

name: 'Setup Badger Environment'
description: 'Checkout source, install dependencies'

runs:
  using: "composite"
  steps:
    - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea  # v4.2.1
