# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
    hooks:
      # https://github.com/pre-commit/pre-commit-hooks?tab=readme-ov-file#hooks-available
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-shebang-scripts-are-executable
      - id: check-symlinks
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: shellcheck
        name: shellcheck
        entry: shellcheck
        language: system
        types:
          - shell
      - id: shfmt
        name: shfmt
        entry: shfmt
        args:
          - --write
        language: system
        types:
          - shell
      - id: yamlfmt
        name: yamlfmt
        entry: yamlfmt
        language: system
        types:
          - yaml
      - id: yamllint
        name: yamllint
        entry: yamllint
        language: system
        types:
          - yaml
      - id: actionlint
        name: actionlint
        language: system
        entry: actionlint
        types:
          - yaml
        files: ^\.github/workflows/
      - id: clippy
        name: clippy
        entry: cargo clippy --fix --allow-dirty
        language: system
        pass_filenames: false
        types:
          - rust
      - id: rustfmt
        name: rustfmt
        entry: rustfmt
        language: system
        types:
          - rust
