# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  # Fail CI on all warnings
  RUSTFLAGS: "-Dwarnings"

jobs:

  lint-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false

      # we rely on mise to get the correct version of pre-commit. this action is mainly
      # useful because it caches the pre-commit execution environment for us.
      - uses: pcrockett/setup-pre-commit@19ef06ee4c041b82a9ad48337154bd4429158560  # v0.1.0

      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea  # v4.2.1
      - run: just lint
      - run: just test
