# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: ["**"]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  # Fail CI on all warnings
  RUSTFLAGS: "-Dwarnings"

jobs:

  lint-test:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/setup-env/
      - run: just lint
      - run: just test
