# yaml-language-server: $schema=https://www.schemastore.org/github-workflow.json

name: Release

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  # Fail CI on all warnings
  RUSTFLAGS: "-Dwarnings"
  TARGETS_TO_BUILD: x86_64-unknown-linux-musl

jobs:

  lint-test:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          persist-credentials: false
      - uses: jdx/mise-action@dad1bfd3df957f44999b559dd69dc1671cb4e9ea  # v4.2.1

      # mise installs pre-commit for us above, but it doesn't setup the necessary
      # caching for the pre-commit execution environment
      - uses: pcrockett/setup-pre-commit@19ef06ee4c041b82a9ad48337154bd4429158560  # v0.1.0

      - run: just lint
      - run: just test
      - name: Build and release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          version="$(./target/x86_64-unknown-linux-musl/release/badger --version | cut -d" " -f2)"
          if [ "${version}" == "" ]; then
            echo "error determining version"
            exit 1
          fi
          mkdir artifacts
          for target in ${TARGETS_TO_BUILD}; do
            just build release "${target}"
            mv "target/${target}/release/badger" "artifacts/badger-${target}"
          done
          gh release create "v${version}" \
            --generate-notes \
            --fail-on-no-commits \
            artifacts/*
